"use strict";
let myName = document.getElementById('name');
let job = document.getElementById('job');
let phone = document.getElementById('phone');
let email = document.getElementById('email');
let address = document.getElementById('address');
let pass1 = document.getElementById('pass1');
let degree1 = document.getElementById('degree1');
let inst1 = document.getElementById('inst1');
let pass2 = document.getElementById('pass2');
let degree2 = document.getElementById('degree2');
let inst2 = document.getElementById('inst2');
let skill1 = document.getElementById('skill1');
let skill2 = document.getElementById('skill2');
let skill3 = document.getElementById('skill3');
let styr = document.getElementById('styr');
let enyr = document.getElementById('enyr');
let com = document.getElementById('com');
let loc = document.getElementById('loc');
let jobt = document.getElementById('jobt');
let acc1 = document.getElementById('acc1');
let acc2 = document.getElementById('acc2');
let acc3 = document.getElementById('acc3');
let pic = document.getElementById('pic');
let subtn = document.getElementById('subtn');
let form = document.getElementById('form');
form?.addEventListener('submit', (a) => {
    a.preventDefault();
    localStorage.setItem("name", myName.value);
    localStorage.setItem("job", job.value);
    localStorage.setItem("phone", phone.value);
    localStorage.setItem("email", email.value);
    localStorage.setItem("address", address.value);
    localStorage.setItem("pass1", pass1.value);
    localStorage.setItem("degree1", degree1.value);
    localStorage.setItem("inst1", inst1.value);
    localStorage.setItem("pass2", pass2.value);
    localStorage.setItem("degree2", degree2.value);
    localStorage.setItem("inst2", inst2.value);
    localStorage.setItem("skill1", skill1.value);
    localStorage.setItem("skill2", skill2.value);
    localStorage.setItem("skill3", skill3.value);
    localStorage.setItem("styr", styr.value);
    localStorage.setItem("enyr", enyr.value);
    localStorage.setItem("com", com.value);
    localStorage.setItem("loc", loc.value);
    localStorage.setItem("jobt", jobt.value);
    localStorage.setItem("acc1", acc1.value);
    localStorage.setItem("acc2", acc2.value);
    localStorage.setItem("acc3", acc3.value);
    if (pic.files && pic.files[0]) {
        let reader = new FileReader();
        reader.addEventListener("load", () => {
            let textImg = reader.result;
            localStorage.setItem("profile_pic", textImg);
        });
        reader.readAsDataURL(pic.files[0]);
    }
    window.location.href = "./resume/resume.html";
});
